services:
  - type: web
    name: converter-plus-plus
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: STARS_PRICE
        value: "399"
      - key: BOT_TOKEN
        sync: false
